language: node_js

os:
  - "linux"
  - "osx"

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - 'node'
  - '10'
  - '9'
  - '8'
  - '6'

before_script:
  - npm prune

after_success:
  - npm run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
